variable "vpc_cidr" {}
variable "vpc_name" {}
variable "public_cidr" {}
variable "public_az" {}
variable "public_subnet_name" {}
variable "private_cidr" {}
variable "private_az" {}
variable "private_subnet_name" {}
variable "igw_name" {}
variable "eip_name" {}
variable "domain_name" {}
variable "nat_name" {}
variable "public_rt_name" {}
variable "private_rt_cidr" {}
variable "public_rt_cidr" {}
variable "private_rt_name" {}
variable "sg_name" {}
variable "ssh_port" {}
variable "ssh_protocol" {}
variable "sg_cidr" {}
variable "http_port" {}
variable "http_protocol" {}
variable "egress_port" {}
variable "egress_protocol" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "public_instance_name" {}
variable "private_instance_name" {}